id: P69956CC8
initial_creation_type: ocr
source_metadata:
  volumes:
    08dce3fe45334368b01f6d8f9f32c962:
      base_file: v098.txt
      image_group_id: I1PD95943
      title: རྩོད་པའི་རིགས་པ་ཞེས་བྱ་བའི་རབ་ཏུ་བྱེད་པ།
      total_pages: 1825
      volume_number: 98
